version: '3'
redis:
  image: 'redis:5.0-alpine'
  command: redis-server
  volumes:
    - redis:/data

sidekiq:
  build: .
  command: bundle exec sidekiq
  volumes:
    - .:/app
  depends_on:
    - redis